version: '3'

services:
  short:
    build: .
    image: short
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - THSL_DB_HOST=db
      - THSL_DB_USER=postgres

  db:
    image: postgres:10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432"
